cassandra:
  contactPoints: 127.0.0.1 # vagrant db machine
  port: 9042
  keyspace: test
  replicationStrategy: SimpleStrategy
  replicationFactor: 1
  readConsistencyLevel: ONE
  writeConsistencyLevel: ONE
  username:
  password:

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: local-queue
          group: producer-consumer
          binder: rabbit
        input:
          destination: local-queue
          group: producer-consumer
          binder: rabbit
          consumer:
            autoBindDlq: true
            republishToDlq: true
            requeueRejected: false
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

