cassandra:
  contactPoints: 127.0.0.1 # vagrant db machine
  port: 9042
  keyspace: test
  replicationStrategy: SimpleStrategy
  replicationFactor: 1
  readConsistencyLevel: ONE
  writeConsistencyLevel: ONE
  username:
  password: